#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Build Language Pack skeleton following Microsoft's vscode-nls format
Source: VS Code official source (legal approach)
Output: Proper language pack structure
"""

import json
from pathlib import Path
from collections import defaultdict

def extract_nls_structure(vscode_dir):
    """
    Extract NLS structure from VS Code source
    Following Microsoft's localization system
    """
    # Structure: module -> key -> value
    structure = defaultdict(dict)
    
    # Find all package.nls.json files (official localization files)
    nls_files = list(vscode_dir.rglob("package.nls.json"))
    
    print(f"Found {len(nls_files)} package.nls.json files")
    
    for nls_file in nls_files:
        try:
            with open(nls_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            # Get module name from path
            rel_path = nls_file.relative_to(vscode_dir)
            module = str(rel_path.parent).replace('\\', '/')
            
            # Store in structure
            for key, value in data.items():
                full_key = f"{module}.{key}"
                structure["contents"][full_key] = value
                
        except Exception as e:
            print(f"Warning: Could not process {nls_file}: {e}")
    
    return structure

def build_language_pack_format(structure):
    """
    Convert to proper language pack format
    Format matches official language packs like Chinese, French, etc.
    """
    language_pack = {
        "": [
            "--------------------------------------------------------------------------------------------",
            "Copyright (c) Microsoft Corporation. All rights reserved.",
            "Licensed under the MIT License. See License.txt in the project root for license information.",
            "--------------------------------------------------------------------------------------------",
            "Do not edit this file. It is machine generated."
        ]
    }
    
    # Merge all content
    if "contents" in structure:
        language_pack.update(structure["contents"])
    
    return language_pack

def create_vietnamese_skeleton(english_pack):
    """
    Create Vietnamese skeleton with English as placeholder
    Ready for translation EN → VI
    """
    vi_pack = {}
    
    for key, value in english_pack.items():
        if key == "":
            # Keep copyright header as-is
            vi_pack[key] = value
        elif isinstance(value, str):
            # Mark for translation
            vi_pack[key] = f"[EN] {value}"
        elif isinstance(value, list):
            vi_pack[key] = [f"[EN] {item}" if isinstance(item, str) else item for item in value]
        elif isinstance(value, dict):
            vi_pack[key] = value  # Keep nested structure
        else:
            vi_pack[key] = value
    
    return vi_pack

if __name__ == "__main__":
    print("="*70)
    print("🇻🇳 MICROSOFT-COMPATIBLE LANGUAGE PACK BUILDER")
    print("="*70)
    print()
    
    vscode_dir = Path(__file__).parent / "vscode-source"
    
    if not vscode_dir.exists():
        print("❌ VS Code source not found!")
        print("Run extract_from_official_source.py first")
        exit(1)
    
    print("📦 Extracting NLS structure from VS Code source...")
    structure = extract_nls_structure(vscode_dir)
    
    print(f"✅ Extracted {len(structure.get('contents', {}))} strings")
    
    # Build English base
    print("📝 Building English base (legal source)...")
    english_pack = build_language_pack_format(structure)
    
    # Save English base
    english_out = Path(__file__).parent / "translations" / "main.i18n.json.english"
    english_out.parent.mkdir(exist_ok=True)
    
    with open(english_out, 'w', encoding='utf-8') as f:
        json.dump(english_pack, f, ensure_ascii=False, indent=2)
    
    print(f"💾 English base: {english_out} ({english_out.stat().st_size/1024:.1f}KB)")
    
    # Create Vietnamese skeleton
    print("🇻🇳 Creating Vietnamese skeleton...")
    vi_skeleton = create_vietnamese_skeleton(english_pack)
    
    vi_out = Path(__file__).parent / "translations" / "main.i18n.json"
    with open(vi_out, 'w', encoding='utf-8') as f:
        json.dump(vi_skeleton, f, ensure_ascii=False, indent=2)
    
    print(f"💾 Vietnamese skeleton: {vi_out} ({vi_out.stat().st_size/1024:.1f}KB)")
    print()
    print("✅ SUCCESS!")
    print()
    print("📋 Summary:")
    print(f"  - English strings: {len(english_pack)}")
    print(f"  - Ready for translation: EN → VI")
    print(f"  - Format: Microsoft Language Pack compatible")
    print(f"  - Source: 100% Legal (VS Code official)")
    print()
    print("🎯 Next steps:")
    print("1. Review main.i18n.json (has [EN] markers)")
    print("2. Translate EN → VI (NOT Chinese!)")
    print("3. Test with VS Code")
    print("4. Publish to marketplace")
